# Profile for deployment on K8S cluster
server:
  port: ${SCORE_CMD_SERVER_PORT}

# gRPC server configuration
grpc:
  server:
    port: ${SCORE_CMD_GRPC_SERVER_PORT}
    # Turn on/off the service listing (for both actuator and grpc) on production
    reflection-service-enabled: ${SCORE_CMD_GRPC_REFLECTION_SERVICE_ENABLED}
    # Turn on/off grpc transport security
    security:
      enabled: ${SCORE_CMD_GRPC_SERVER_SECURITY_ENABLED}

spring:
  config:
    location: classpath:/application-prod.yml
  banner:
    location: classpath:/prod/banner.txt

  # Mongo properties
  data:
    mongodb:
      host: ${MONGO_HOSTNAME}
      port: ${ME_CONFIG_MONGODB_PORT}
      database: ${MONGO_INITDB_DATABASE}
      username: ${MONGO_ADMIN_USERNAME}
      password: ${MONGO_ADMIN_PASSWORD}
      authentication-database: ${MONGO_INITDB_DATABASE}

  # Kafka properties
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOSTNAME_1}:${KAFKA_BROKER_PORT_1},${KAFKA_HOSTNAME_2}:${KAFKA_BROKER_PORT_2},${KAFKA_HOSTNAME_3}:${KAFKA_BROKER_PORT_3}

# Actuator configuration
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        # exposed endpoints
        include: health, info, prometheus

# Keycloak configuration
keycloak:
  schema: ${KEYCLOAK_SCHEMA} # schema
  hostname: ${KEYCLOAK_HOSTNAME} # hostname
  port: ${KEYCLOAK_PORT} # port number
  realm: ${KEYCLOAK_REALM} # realm name
  client-id: ${KEYCLOAK_CLIENT_ID} # client id
  secret: ${KEYCLOAK_SECRET} # secret

# OpenApi configuration
api:
  hostname: ${OPEN_API_URL}
