version: "3.8"

# Project name
name: rps-app

services:
  # Elasticsearch stores and indexes the data.
  elasticsearch:
    image: elastic/elasticsearch:${ELASTICSEARCH_VERSION}
    restart: on-failure
    ports: # Important: In a production environment you should remove the external port that kept here for debugging purposes.
      - 9200:9200 # Elasticsearch HTTP, external port / container port (Elasticsearch HTTP)
      - 9300:9300 # Elasticsearch TCP transport, external port / container port (Elasticsearch TCP transport)
    env_file:
      - .env
    environment:
      - ES_JAVA_OPTS=-Xms1500m -Xmx1500m
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      - discovery.type=single-node
    volumes:
      - ./infrastructure/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch-data:/usr/share/elasticsearch/data # Persistence data
    networks:
      - ${BACKEND_NETWORK}
    deploy:
      replicas: 1

  # Logstash is used to collect, parse, transform, and buffer data from a variety of sources.
  logstash:
    image: elastic/logstash:${LOGSTASH_VERSION}
    restart: on-failure
    ports: # Important: In a production environment you should remove the external port that kept here for debugging purposes.
      - 5044:5044 # Logstash Beats input, external port / container port (Logstash Beats input)
      - 50000:50000/tcp # external port / container port (Logstash TCP input)
      - 50000:50000/udp # external port / container port (Logstash UDP input)
      - 9600:9600 # external port / container port (Logstash monitoring API)
    env_file:
      - .env
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
      - LOGSTASH_INTERNAL_PASSWORD=${LOGSTASH_INTERNAL_PASSWORD}
    volumes:
      - ./infrastructure/elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf # Pipeline configuration
      - ./infrastructure/elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on:
      - elasticsearch
    networks:
      - ${BACKEND_NETWORK}
    deploy:
      replicas: 1

  # Kibana acts as an analytics and visualization layer on top of Elasticsearch.
  kibana:
    image: elastic/kibana:${KIBANA_VERSION}
    restart: on-failure
    ports: # Important: In a production environment you should remove the external port that kept here for debugging purposes.
      - 5601:5601 # external port / container port
    env_file:
      - .env
    environment:
      - KIBANA_SYSTEM_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
    volumes:
      - ./infrastructure/elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - ${BACKEND_NETWORK}
    deploy:
      replicas: 1

# persistent volumes location
volumes:
  elasticsearch-data:
    driver: local
  filebeat-data:
    driver: local

# networks
networks:
  rps_net:
    name: ${BACKEND_NETWORK}
