version: "3.8"

# Project name
name: rps-app

services:
  # The Score query microservice provides REST and gRPC APIs for the RPS game.
  score-qry-service:
    container_name: score-qry-service
    #    image: hokushin/score-qry-service:${SCORE_QRY_SRV_VERSION}
    build:
      context: .
      dockerfile: ./docker/score-qry-service/Dockerfile
    hostname: ${SCORE_QRY_SRV_HOSTNAME}
    restart: on-failure
    environment:
      - JVM_OPTS=-Xmx8g -Xms8g -XX:MaxPermSize=1024m
      - SERVER_PORT=${SCORE_QRY_SERVER_PORT}
      - GRPC_SERVER_PORT=${SCORE_QRY_GRPC_SERVER_PORT}
    labels:
      collect_logs_with_filebeat: true
      decode_log_event_to_json: true
    ports: # Important: In a production environment you should remove the external port that kept here for debugging purposes.
      - ${SCORE_QRY_SERVER_PORT}:80 # external port / container port
      - ${SCORE_QRY_GRPC_SERVER_PORT}:6565 # external port / container port
    env_file:
      - .env
    networks:
      - ${BACKEND_NETWORK}
    deploy:
      replicas: 1

# networks
networks:
  rps_net:
    name: ${BACKEND_NETWORK}
