version: "3.8"

# Project name
name: rps-app

services:
  # Prometheus (metrics database) - http://<host-ip>:9090
  prometheus:
    container_name: prometheus
    image: prom/prometheus:${PROMETHEUS_VERSION}
    hostname: ${PROMETHEUS_HOSTNAME}
    restart: on-failure
    ports: # Important: In a production environment you should remove the external port that kept here for debugging purposes.
      - 9090:9090 # external port / container port
    env_file:
      - .env
    volumes:
      - ./infrastructure/metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # prometheus configuration file
      - prometheus-data:/etc/prometheus # creating a volume to save Prometheus data locally
    networks:
      - ${BACKEND_NETWORK}
    deploy:
      replicas: 1

  # Grafana (visualize metrics) - http://<host-ip>:3000
  grafana:
    container_name: grafana
    image: grafana/grafana:${GF_VERSION}
    hostname: ${GF_HOSTNAME}
    restart: on-failure
    user: "104" # setting up the user to use over the Docker container to allow reads/writes over disk
    ports: # Important: In a production environment you should remove the external port that kept here for debugging purposes.
      - 3000:3000 # external port / container port
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./infrastructure/metrics/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana # creating a volume to save Grafana data locally
    depends_on:
      - prometheus
    networks:
      - ${BACKEND_NETWORK}
    deploy:
      replicas: 1

# persistent volumes location
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

# networks
networks:
  rps_net:
    name: ${BACKEND_NETWORK}
