# Secret holds MariaDB confidential data
apiVersion: v1 # K8S API version
kind: Secret
metadata:
  name: mariadb-secret
  namespace: kube-db # The name of the namespace
  labels:
    app: mariadb
    tier: database
type: Opaque
data:
  # Values encoded to base 64 format https://www.base64encode.org
  mariadb-root-password: MTIzNDU= # echo -n '12345' | base64
