# Secret holds RPS Game Command Microservice confidential data
apiVersion: v1 # K8S API version
kind: Secret
metadata:
  name: rps-cmd-service-secret
  namespace: rps-app-dev # The name of the namespace
  labels:
    app: rps-cmd-service
    tier: backend
    environment: development
type: Opaque
data:
  # Values encoded to base 64 format https://www.base64encode.org
  mongodb-admin-username: YWRtaW4= # echo -n 'admin' | base64
  mongodb-admin-password: bW9uZ28xMjM0NQ== # echo -n 'mongo12345' | base64
  keycloak-secret: HVxWhjNes0vU3FyxETpmBcYXyV0WVAgw
