# Secret holds RPS Game Query Microservice confidential data
apiVersion: v1 # K8S API version
kind: Secret
metadata:
  name: rps-qry-service-secret
  namespace: rps-app-dev # The name of the namespace
  labels:
    app: rps-qry-service
    tier: backend
    environment: development
type: Opaque
data:
  # Values encoded to base 64 format https://www.base64encode.org
  mariadb-root-username: cm9vdA== # echo -n 'root' | base64
  mariadb-root-password: MTIzNDU= # echo -n '12345' | base64
  redis-password: MTIzNDU= # echo -n '12345' | base64
  keycloak-secret: HVxWhjNes0vU3FyxETpmBcYXyV0WVAgw
