# RPS Game Query microservice Prometheus service monitor
apiVersion: monitoring.coreos.com/v1 # K8S API version
kind: ServiceMonitor
metadata:
  name: rps-qry-service-sm
  namespace: rps-app-dev # The name of the namespace
  labels:
    app: rps-qry-service
    tier: backend
    environment: development
    release: prometheus # allows prometheus to discover it
spec:
  selector:
    matchLabels:
      app: rps-qry-service
      tier: backend
      environment: development
  endpoints: # an endpoint to use to scrape metrics
    - port: http-8080
      path: "/actuator/prometheus" # Spring Boot app exposes the Prometheus-formatted metrics to this endpoint
