# ConfigMap holds information about Elasticsearch curator configuration files
apiVersion: v1 # K8S API version
kind: ConfigMap
metadata:
  name: curator-configmap
  namespace: kube-elk # The name of the namespace
  labels:
    app: elasticsearch
    tier: infrastructure
data:

  config.yml: |-
    client:
    hosts:
        - ['${CURATOR_ELASTICSEARCH_URL:elasticsearch-svc.kube-elk}']
    port: 9200
    url_prefix:
    use_ssl: False
    certificate:
    client_cert:
    client_key:
    ssl_no_validate: False
    username:
    password:
    timeout: 30
    master_only: False

    logging:
    loglevel: INFO
    logfile:
    logformat: default
    blacklist: ['elasticsearch', 'urllib3']

  actions.yml: |-
    actions:
        1:
            action: delete_indices
            description: "Delete indices older than 20 days"
            options:
            ignore_empty_list: True
            filters:
            - filtertype: age
                source: creation_date
                direction: older
                unit: days
                unit_count: 20
