# ConfigMap holds information about Logstash configuration files
apiVersion: v1 # K8S API version
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: kube-elk # The name of the namespace
  labels:
    app: logstash
    tier: infrastructure
data:

  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: "false"

  logstash.conf: |
    input {
      beats {
        port => "5044"
      }
    }

    filter {
      mutate {
        rename => ["host", "hostname"]
        convert => {"hostname" => "string"}
      }
    }

    output {
      stdout {
        codec => rubydebug
      }
      elasticsearch {
        hosts => "http://elasticsearch-svc.kube-elk"
      }
    }
