# Secret holds MongoDB confidential data
apiVersion: v1 # K8S API version
kind: Secret
metadata:
  name: mongodb-secret
  namespace: kube-nosql-db # The name of the namespace
  labels:
    app: mongodb
    tier: database
type: Opaque
data:
  # Values encoded to base 64 format https://www.base64encode.org
  mongodb-root-username: cm9vdA== # echo -n 'root' | base64
  mongodb-root-password: bW9uZ28xMjM0NQ== # echo -n 'mongo12345' | base64
