# Secret holds Redis confidential data
apiVersion: v1 # K8S API version
kind: Secret
metadata:
  name: redis-secret
  namespace: kube-cache # The name of the namespace
  labels:
    app: redis
    tier: cache
type: Opaque
data:
  # Values encoded to base 64 format https://www.base64encode.org
  redis-password: MTIzNDU= # echo -n '12345' | base64
