# Kibana deployment configuration
# Web interface for searching and visualizing logs
apiVersion: apps/v1 # K8S API version
kind: Deployment
metadata: # Describes information about the app
  name: kibana-deployment
  namespace: kube-elk # The name of the namespace
  labels:
    app: kibana
    tier: infrastructure
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: kibana
      tier: infrastructure
  strategy:
    type: RollingUpdate # It replaces the existing version of pods with a new version, updating pods slowly one by one, without cluster downtime
    rollingUpdate:
      maxSurge: 2 # Specifies the maximum number of pods the Deployment is allowed to create at one time
      maxUnavailable: 1 # Specifies the maximum number of pods that are allowed to be unavailable during the rollout
  template: # Blueprint for pods
    metadata:
      labels:
        app: kibana
        tier: infrastructure
    spec: # Specification for pods
      containers:
        - name: kibana
          image: elastic/kibana:6.8.23
          imagePullPolicy: IfNotPresent
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
          ports:
            - name: http-5601
              protocol: TCP
              containerPort: 5601
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
