# Logstash deployment configuration
# The server component of Logstash that processes incoming logs
apiVersion: apps/v1 # K8S API version
kind: Deployment
metadata: # Describes information about the app
  name: logstash-deployment
  namespace: kube-elk # The name of the namespace
  labels:
    app: logstash
    tier: infrastructure
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: logstash
      tier: infrastructure
  strategy:
    type: RollingUpdate # It replaces the existing version of pods with a new version, updating pods slowly one by one, without cluster downtime
    rollingUpdate:
      maxSurge: 2 # Specifies the maximum number of pods the Deployment is allowed to create at one time
      maxUnavailable: 1 # Specifies the maximum number of pods that are allowed to be unavailable during the rollout
  template: # a blueprint for pods
    metadata:
      labels:
        app: logstash
        tier: infrastructure
    spec: # specification for pods
      hostname: logstash
      containers:
        - name: logstash
          image: elastic/logstash:6.8.23
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp-5044
              protocol: TCP
              containerPort: 5044 # The port that the container is running on in the cluster
          env: # Setting environmental variables
            - name: LS_JAVA_OPTS
              value: "-Xmx2g -Xms2g"
          # Mount volume from persistent volume claim
          volumeMounts:
            - name: logstash-pipeline-volume # a mount for pipeline
              mountPath: /usr/share/logstash/pipeline
            - name: config-volume # a mount for config
              mountPath: /etc/logstash/config
              readOnly: true
      #          resources:
      #            limits:
      #              cpu: 100m
      #              memory: 100Mi
      #            requests:
      #              cpu: 50m
      #              memory: 50Mi
      volumes:
        # Previously defined ConfigMap object
        - name: config-volume
          configMap:
            name: logstash-configmap
            items:
              - key: logstash.yml
                path: logstash.yml
        - name: logstash-pipeline-volume
          configMap:
            name: logstash-configmap
            items:
              - key: logstash.conf
                path: logstash.conf
