# Score Command microservice deployment configuration
apiVersion: apps/v1 # K8S API version
kind: Deployment
metadata: # Describes information about the app
  name: score-cmd-service-deployment
  namespace: rps-app-dev # The name of the namespace
  labels:
    app: score-cmd-service
    tier: backend
    environment: development
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: score-cmd-service
      tier: backend
      environment: development
  strategy:
    type: RollingUpdate # It replaces the existing version of pods with a new version, updating pods slowly one by one, without cluster downtime
    rollingUpdate:
      maxSurge: 2 # Specifies the maximum number of pods the Deployment is allowed to create at one time
      maxUnavailable: 1 # Specifies the maximum number of pods that are allowed to be unavailable during the rollout
  template: # a blueprint for pods
    metadata:
      labels:
        app: score-cmd-service
        tier: backend
        environment: development
      annotations: # https://www.elastic.co/guide/en/beats/filebeat/current/running-on-kubernetes.html
        co.elastic.logs/enabled: "true"
        co.elastic.logs.json-logging/json.keys_under_root: "true"
        co.elastic.logs.json-logging/json.add_error_key: "true"
        co.elastic.logs.json-logging/json.message_key: "message"
    spec: # specification for pods
      terminationGracePeriodSeconds: 10 # It gives microservice 10 seconds to shut down gracefully upon receiving a SIGTERM signal
      containers:
        - name: score-cmd-service
          image: hokushin/score-cmd-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-8080
              protocol: TCP
              containerPort: 8080 # The port that the container is running on in the cluster
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 50m
          env: # Setting environmental variables
            - name: KAFKA_HOSTNAME_1
              value: "kafka-1"
            - name: KAFKA_BROKER_PORT_1
              value: "9093"
            - name: KAFKA_HOSTNAME_2
              value: "kafka-2"
            - name: KAFKA_BROKER_PORT_2
              value: "9094"
            - name: KAFKA_HOSTNAME_3
              value: "kafka-3"
            - name: KAFKA_BROKER_PORT_3
              value: "9095"
            - name: MONGO_HOSTNAME
              valueFrom:
                configMapKeyRef: # Using ConfigMap
                  name: score-cmd-service-configmap
                  key: mongodb-url
            - name: ME_CONFIG_MONGODB_PORT
              valueFrom:
                configMapKeyRef: # Using ConfigMap
                  name: score-cmd-service-configmap
                  key: mongodb-port
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef: # Using ConfigMap
                  name: score-cmd-service-configmap
                  key: mongodb-database
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef: # Using Secrets
                  name: score-cmd-service-secret
                  key: mongodb-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: # Using Secrets
                  name: score-cmd-service-secret
                  key: mongodb-root-password
            - name: OPEN_API_URL
              value: "score-cmd-service"
            - name: SCORE_CMD_SERVER_PORT
              value: "8080"
            - name: SCORE_CMD_GRPC_SERVER_PORT
              value: "6565"
          # Mount volume from persistent volume claim
          volumeMounts:
            - name: config-volume # a mount for config
              mountPath: /etc/score-cmd-service/config
              readOnly: true
            - name: secrets-volume # a mount for secrets
              mountPath: /etc/score-cmd-service/secrets
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: score-cmd-service-configmap
            #defaultMode: 0544
        - name: secrets-volume
          secret:
            secretName: score-cmd-service-secret
            optional: true
#          readinessProbe:
#            httpGet:
#              port: 8080
#              path: /actuator/health/readiness
#            initialDelaySeconds: 5
#            timeoutSeconds: 1
#            periodSeconds: 5
#          livenessProbe:
#            httpGet:
#              port: 8080
#              path: /actuator/health/liveness
#            initialDelaySeconds: 30
#            timeoutSeconds: 1
#            periodSeconds: 5
