# Profile for deployment on docker-compose
server:
  port: ${RPS_CMD_SERVER_PORT}

# gRPC server configuration
grpc:
  server:
    port: ${RPS_CMD_GRPC_SERVER_PORT}
    # Turn on/off the service listing (for both actuator and grpc) on production
    reflection-service-enabled: ${RPS_CMD_GRPC_REFLECTION_SERVICE_ENABLED}
    # Turn on/off grpc transport security
    security:
      enabled: ${RPS_CMD_GRPC_SERVER_SECURITY_ENABLED}

spring:
  config:
    location: classpath:/application-docker.yml
  banner:
    location: classpath:/docker/banner.txt

  # Mongo properties
  data:
    mongodb:
      host: ${MONGO_HOSTNAME}
      port: ${ME_CONFIG_MONGODB_PORT}
      database: ${RPS_DATABASE}
      username: ${MONGO_ADMIN_USERNAME}
      password: ${MONGO_ADMIN_PASSWORD}
      authentication-database: ${MONGO_INITDB_DATABASE}

  # Kafka properties
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOSTNAME_1}:${KAFKA_BROKER_PORT_1},${KAFKA_HOSTNAME_2}:${KAFKA_BROKER_PORT_2},${KAFKA_HOSTNAME_3}:${KAFKA_BROKER_PORT_3}

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        # exposing all endpoints
        include: "*"
  endpoint:
    health:
      show-details: always

# OpenApi configuration
api:
  dev:
    server:
      base-url: http://${OPEN_API_URL}${server.servlet.context-path}
  prod:
    server:
      base-url: http://${OPEN_API_URL}${server.servlet.context-path}
