# Profile for integration tests
server:
  port: 8081

# gRPC server configuration
grpc:
  server:
    port: 6790
    # Turn on/off the service listing (for both actuator and grpc)
    reflection-service-enabled: true

spring:
  config:
    location: classpath:/application.yml
  banner:
    location: classpath:/it/banner.txt

  # Mongo properties
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rpsDB
      username: root
      password: mongo12345
      authentication-database: admin # name of the authentication database

  # Kafka properties
  kafka:
    producer:
      bootstrap-servers: kafka.internal:9092

# Keycloak configuration
keycloak:
  schema: http # schema
  hostname: localhost # hostname
  port: 8180 # port number
  url: ${keycloak.schema}://${keycloak.hostname}:${keycloak.port} # url
  realm: rps-dev # realm name
  client-id: oauth2-proxy # client id
  secret: HVxWhjNes0vU3FyxETpmBcYXyV0WVAgw # secret

# OpenApi configuration
api:
  schema: http # schema
  hostname: localhost
  url: ${api.schema}://${api.hostname}:${server.port}${server.servlet.context-path}
  kc-hostname: localhost
