pipeline {
	agent {
		label "default"
	}
	stages {
		stage('Checkout Source') {
			steps {
				script {
					git url: 'https://github.com/hokushin118/rps-microservices.git', credentialsId: 'github_credentials'
					sh 'ls -la'
				}
			}
		}
		stage('Build') {
			agent {
				label "maven"
			}
			steps {
				sh 'ls -la'
				sh 'mvn -version'
				sh 'mvn clean compile -Pprod'
			}
		}
		stage('Unit Tests') {
			agent {
				label "maven"
			}
			steps {
				sh 'mvn test -Pprod'
			}
		}
        stage('Integration Tests') {
			agent {
				label "maven"
			}
			steps {
				sh 'mvn verify -DskipTests -Djib.skip=true -Pprod'
			}
		}
		stage('Build & Push image') {
			agent {
				label "maven"
			}
			steps {
				sh 'mvn -Pprod -Djib.to.auth.username=<login> -Djib.to.auth.password=<pwd> jib:build'
			}
		}
		stage('Deploy to K8S cluster') {
			steps {
				script {
				    kubernetesDeploy(configs: 'k8s/configmaps/rps-cmd-service-configmap.yml',
				                               'k8s/secrets/rps-cmd-service-secret.yml',
				                               'k8s/deployments/rps-cmd-service-deployment.yml',
				                               'k8s/services/rps-cmd-service-svc.yml')
				}
			}
		}
	}
}
