# MongoDB headless ClusterIP service
apiVersion: v1 # K8S API version
kind: Service
metadata:
  name: mongodb-svc
  namespace: kube-nosql-db # The name of the namespace
  labels:
    app: mongodb
    tier: database
spec:
  selector:
    app: mongodb
    tier: database
  ports:
    - name: tcp-27017
      protocol: TCP
      port: 27017 # The port that the service is running on in the cluster
  clusterIP: None # Headless service
