# ConfigMap holds information about RPS Game Command microservice configuration files
apiVersion: v1 # K8S API version
kind: ConfigMap
metadata:
  name: rps-cmd-service-configmap
  namespace: rps-app-dev # The name of the namespace
  labels:
    app: rps-cmd-service
    tier: backend
    environment: development
data:

  server-port: "8080"
  grpc-server-port: "6565"
  mongodb-url: mongodb-sts-0.mongodb-svc.kube-nosql-db
  mongodb-port: "27017"
  mongodb-database: rpsDB
