# ConfigMap holds information about RPS Game Query microservice configuration files
apiVersion: v1 # K8S API version
kind: ConfigMap
metadata:
  name: rps-qry-service-configmap
  namespace: rps-app-dev # The name of the namespace
  labels:
    app: rps-qry-service
    tier: backend
    environment: development
data:

  server-port: "8080"
  grpc-server-port: "6565"
  mariadb-url: mariadb-sts-0.mariadb-svc.kube-db
  mariadb-port: "3306"
  mariadb-database: rpsDB
  redis-url: redis-sts-0.redis-svc.kube-cache
  redis-port: "6379"
  kafka-broker-0-hostname: kafka-0.kafka-headless.kube-kafka.svc.cluster.local
  kafka-broker-1-hostname: kafka-1.kafka-headless.kube-kafka.svc.cluster.local
  kafka-broker-2-hostname: kafka-2.kafka-headless.kube-kafka.svc.cluster.local
  kafka-broker-0-port: "9092"
  kafka-broker-1-port: "9092"
  kafka-broker-2-port: "9092"
