# ConfigMap holds information about RPS Game Command microservice configuration files
apiVersion: v1 # K8S API version
kind: ConfigMap
metadata:
  name: rps-cmd-service-configmap
  namespace: rps-app-dev # The name of the namespace
  labels:
    app: rps-cmd-service
    tier: backend
    environment: development
data:

  server-port: "8080"
  grpc-server-port: "50051"
  grpc-server-security-enabled: "false"
  grpc-reflection-service-enabled: "on" # Turn off the grpc service listing (for both actuator and grpc) on production
  grpc-security-enabled: "false" # Turn on the grpc service transport security on production
  grpc-server-security-certificate-chain: "file:/etc/ssl/certs/grpc.rps.cmd.internal.crt"
  grpc-server-security-private-key: "file:/etc/ssl/certs/grpc.rps.cmd.internal.key"
  grpc-server-security-trust-cert-collection: "file:/etc/ssl/certs/rps.clients.crt.collection" # mTLS - trusted clients cert collection, cat client*.crt > trusted-clients.crt.collection
  grpc-server-security-client-auth: "REQUIRE" # mTLS - makes client certificate authentication mandatory
  mongodb-url: mongodb-sts-0.mongodb-svc.kube-nosql-db
  mongodb-port: "27017"
  mongodb-admin-database: admin
  mongodb-database: rpsDB
  kafka-broker-0-hostname: kafka-0.kafka-headless.kube-kafka.svc.cluster.local
  kafka-broker-1-hostname: kafka-1.kafka-headless.kube-kafka.svc.cluster.local
  kafka-broker-2-hostname: kafka-2.kafka-headless.kube-kafka.svc.cluster.local
  kafka-broker-0-port: "9092"
  kafka-broker-1-port: "9092"
  kafka-broker-2-port: "9092"
