# ConfigMap holds information about Score Query microservice configuration files
apiVersion: v1 # K8S API version
kind: ConfigMap
metadata:
  name: score-qry-service-configmap
  namespace: rps-app-dev # The name of the namespace
  labels:
    app: score-qry-service
    tier: backend
    environment: development
data:

  server-port: "8080"
  grpc-server-port: "6565"
  mariadb-url: mariadb-sts-0.mariadb-svc.kube-db
  mariadb-port: "3306"
  mariadb-database: scoreDB
  redis-url: redis-sts-0.redis-svc.kube-cache
  redis-port: "6379"
