# Profile for deployment on K8S cluster
server:
  port: ${SCORE_QRY_SERVER_PORT}

# gRPC server configuration
grpc:
  server:
    port: ${SCORE_QRY_GRPC_SERVER_PORT}
    # Turn off the service listing (for both actuator and grpc) on production
    reflection-service-enabled: ${SCORE_QRY_GRPC_REFLECTION_SERVICE_ENABLED}
    # Turn off grpc transport security
    security:
      enabled: ${SCORE_QRY_GRPC_SERVER_SECURITY_ENABLED}

spring:
  config:
    location: classpath:/application-prod.yml
  banner:
    location: classpath:/prod/banner.txt

  jpa:
    # show log for each sql query
    show-sql: true
    # schema will be automatically created afresh for every start of the application
    hibernate:
      ddl-auto: update
    # allows Hibernate to generate SQL optimized for a particular DBMS
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        # format sql query
        format_sql: true

  # MariaDB database connection configuration
  datasource:
    url: jdbc:mariadb://${MARIADB_URL}/${SCORE_DATABASE}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${MARIADB_ROOT_USER}
    password: ${MARIADB_ROOT_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  # Flyway configuration
  flyway:
    url: jdbc:mariadb://${MARIADB_HOSTNAME}:${MARIADB_PORT}
    user: ${MARIADB_ROOT_USER}
    password: ${MARIADB_ROOT_PASSWORD}
    schemas: ${SCORE_DATABASE}

  # Kafka properties
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOSTNAME_1}:${KAFKA_BROKER_PORT_1},${KAFKA_HOSTNAME_2}:${KAFKA_BROKER_PORT_2},${KAFKA_HOSTNAME_3}:${KAFKA_BROKER_PORT_3}

  # Cache configuration
  cache:
    type: redis
    redis:
      cache-null-values: true

  # Redis configuration
  redis:
    host: ${REDIS_HOSTNAME}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

# Actuator configuration
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        # exposed endpoints
        include: health, info, prometheus

# Keycloak configuration
keycloak:
  schema: ${KEYCLOAK_SCHEMA} # schema
  hostname: ${KEYCLOAK_HOSTNAME} # hostname
  port: ${KEYCLOAK_PORT} # port number
  url: ${KEYCLOAK_SCHEMA}://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT} # url
  realm: ${KEYCLOAK_REALM} # realm name
  client-id: ${KEYCLOAK_CLIENT_ID} # client id
  secret: ${KEYCLOAK_SECRET} # secret

# OpenApi configuration
api:
  schema: ${SCORE_QRY_SRV_SCHEMA} # schema
  hostname: ${OPEN_API_URL}
  url: ${api.schema}://${api.hostname}:${server.port}${server.servlet.context-path}
  kc-hostname: ${keycloak.hostname}
