# Kibana ClusterIP service
apiVersion: v1 # K8S API version
kind: Service
metadata:
  name: kibana-svc
  namespace: kube-elk # The name of the namespace
  labels:
    app: kibana
    tier: infrastructure
spec:
  selector:
    app: kibana
    tier: infrastructure
  ports:
    - name: http-5601
      protocol: TCP
      port: 5601 # The port that the service is running on in the cluster
      targetPort: 5601 # The port exposed by the service
  type: ClusterIP # Type of the service, here our application is only accessible in the K8S private network and can’t be accessed from the outside world
