# Logstash ClusterIP service
apiVersion: v1 # K8S API version
kind: Service
metadata:
  name: logstash-svc
  namespace: kube-elk # The name of the namespace
  labels:
    app: logstash
    tier: infrastructure
spec:
  selector:
    app: logstash
    tier: infrastructure
  ports:
    - name: tcp-5044
      protocol: TCP
      port: 5044 # The port that the service is running on in the cluster
      targetPort: 5044 # The port exposed by the service
    - name: tcp-9600
      protocol: TCP
      port: 9600 # The port that the service is running on in the cluster
      targetPort: 9600 # The port exposed by the service
  type: ClusterIP # Type of the service, here our application is only accessible in the K8S private network and can’t be accessed from the outside world
