# MongoDB Express ClusterIP service
apiVersion: v1 # K8S API version
kind: Service
metadata:
  name: mongodb-express-svc
  namespace: kube-nosql-db # The name of the namespace
  labels:
    app: mongodb-express
    tier: database
spec:
  selector:
    app: mongodb-express
    tier: database
  ports:
    - name: http-8081
      protocol: TCP
      port: 8081 # The port that the service is running on in the cluster
      targetPort: 8081 # The port exposed by the service
  type: ClusterIP # Type of the service, here our application is only accessible in the K8S private network and can’t be accessed from the outside world
