# Profile for deployment on docker-compose
server:
  port: ${RPS_QRY_SERVER_PORT}

# gRPC server configuration
grpc:
  server:
    port: ${RPS_QRY_GRPC_SERVER_PORT}
    # Turn on/off the service listing (for both actuator and grpc) on production
    reflection-service-enabled: ${RPS_QRY_GRPC_REFLECTION_SERVICE_ENABLED}
    # Turn on/off grpc transport security
    security:
      enabled: ${RPS_QRY_GRPC_SERVER_SECURITY_ENABLED}

spring:
  config:
    location: classpath:/application-docker.yml
  banner:
    location: classpath:/docker/banner.txt

  jpa:
    # show log for each sql query
    show-sql: true
    # schema will be automatically created afresh for every start of the application
    hibernate:
      ddl-auto: update
    # allows Hibernate to generate SQL optimized for a particular DBMS
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        # format sql query
        format_sql: true

  # MariaDB database connection configuration
  datasource:
    url: jdbc:mariadb://${MARIADB_URL}/${RPS_DATABASE}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${MARIADB_ROOT_USER}
    password: ${MARIADB_ROOT_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  # Flyway configuration
  flyway:
    url: jdbc:mariadb://${MARIADB_HOSTNAME}:${MARIADB_PORT}
    user: ${MARIADB_ROOT_USER}
    password: ${MARIADB_ROOT_PASSWORD}
    schemas: ${RPS_DATABASE}

  # Kafka properties
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOSTNAME_1}:${KAFKA_BROKER_PORT_1},${KAFKA_HOSTNAME_2}:${KAFKA_BROKER_PORT_2},${KAFKA_HOSTNAME_3}:${KAFKA_BROKER_PORT_3}

  # Cache configuration
  cache:
    type: redis
    redis:
      cache-null-values: true

  # Redis configuration
  redis:
    host: ${REDIS_HOSTNAME}
    port: ${REDIS_PORT}
    password:

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        # exposing all endpoints
        include: "*"
  endpoint:
    health:
      show-details: always

# Keycloak configuration
keycloak:
  schema: ${KEYCLOAK_SCHEMA} # schema
  hostname: ${KEYCLOAK_HOSTNAME} # hostname
  port: ${KEYCLOAK_PORT} # port number
  url: ${KEYCLOAK_SCHEMA}://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT} # url
  realm: ${KEYCLOAK_REALM} # realm name
  client-id: ${KEYCLOAK_CLIENT_ID} # client id
  secret: ${KEYCLOAK_SECRET} # secret

# OpenApi configuration
api:
  schema: ${RPS_QRY_SRV_SCHEMA} # schema
  hostname: ${OPEN_API_URL}
  url: ${api.schema}://${api.hostname}${server.servlet.context-path}
  kc-hostname: ${KEYCLOAK_EXT_HOSTNAME}
