# Profile for integration tests
server:
  port: 8082

# gRPC server configuration
grpc:
  server:
    port: 6791
    # Turn on/off the service listing (for both actuator and grpc)
    reflection-service-enabled: true

spring:
  config:
    location: classpath:/application-it.yml
  banner:
    location: classpath:/it/banner.txt

  jpa:
    # show log for each sql query
    show-sql: true
    hibernate:
      # schema will be automatically created afresh for every start of the application
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        # format sql query
        format_sql: true

  datasource:
    url: jdbc:h2:mem:rpsDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: root
    password: 12345
    driver-class-name: org.h2.Driver

  h2:
    # enables h2 console at http://localhost:8080/h2-console
    console:
      enabled: true
      # relative path to the console
      path: /h2-console
      settings:
        # disable remote access
        web-allow-others: false
        # prevent trace output
        trace: false

  # Flyway configuration
  flyway:
    enabled: false

  # Kafka properties
  kafka:
    consumer:
      bootstrap-servers: kafka.internal:9092

  # Cache configuration
  cache:
    type: simple

# Keycloak configuration
keycloak:
  schema: http # schema
  hostname: localhost # hostname
  port: 8180 # port number
  realm: rps-dev # realm name
  client-id: oauth2-proxy # client id
  secret: HVxWhjNes0vU3FyxETpmBcYXyV0WVAgw # secret

# OpenApi configuration
api:
  hostname: localhost
