# Profile for deployment on local machine
server:
  port: 8082
  error:
    include-stacktrace: always

# gRPC server configuration
grpc:
  server:
    port: 6791
    # Turn on/off the service listing (for both actuator and grpc)
    reflection-service-enabled: true

spring:
  config:
    location: classpath:/application-dev.yml
  banner:
    location: classpath:/dev/banner.txt

  jpa:
    # show log for each sql query
    show-sql: true
    hibernate:
      # schema will be automatically created afresh for every start of the application
      ddl-auto: update
    # allows Hibernate to generate SQL optimized for a particular DBMS
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        # format sql query
        format_sql: true

  # MariaDB database connection configuration
  datasource:
    url: jdbc:mariadb://localhost:3306/rpsDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: org.mariadb.jdbc.Driver

  # Flyway configuration
  flyway:
    url: jdbc:mariadb://localhost:3306
    user: root
    password: 12345
    schemas: rpsDB

  # Kafka properties
  kafka:
    consumer:
      bootstrap-servers: kafka.internal:9092

  # Cache configuration
  cache:
    type: redis
    redis:
      cache-null-values: true

  # Redis configuration
  redis:
    host: localhost
    port: 6379

# Keycloak configuration
keycloak:
  schema: http # schema
  hostname: localhost # hostname
  port: 8180 # port number
  realm: rps-dev # realm name
  client-id: oauth2-proxy # client id
  secret: HVxWhjNes0vU3FyxETpmBcYXyV0WVAgw # secret

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        # exposing all endpoints
        include: "*"
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    # Autoconfigure logging configuration
    org.springframework.boot.autoconfigure: debug
    # Show bind values
    org.hibernate.type.descriptor.sql: trace

# OpenApi configuration
api:
  hostname: localhost
