# Play new game v1

POST http://{{host}}:{{rps_cmd_port}}/rps-cmd-api/v1/games HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

"ROCK"

###

# Play new game v1.1

POST http://{{host}}:{{rps_cmd_port}}/rps-cmd-api/v1.1/games HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

"ROCK"

###

# Play new game v2

POST http://{{host}}:{{rps_cmd_port}}/rps-cmd-api/v2/games HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "hand": "ROCK"
}

###

# Play new game v2.1

POST http://{{host}}:{{rps_cmd_port}}/rps-cmd-api/v2.1/games HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "hand": "ROCK"
}

###
