# Get list of my games v1

GET http://{{host}}:{{rps_qry_port}}/rps-qry-api/v1/games HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# Get list of my games v2

GET http://{{host}}:{{rps_qry_port}}/rps-qry-api/v2/games HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
